server:
  port: 8099
spring:
  datasource:
    url: jdbc:mysql://47.120.33.1:3306/heima?useSSL=false
    username: root
    password: 52ms1.MYSQL
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 120.79.85.39
    port: 5672
    username: itcast
    password: 123321
    virtual-host: /
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: cn.itcast.hotel.pojo
  global-config:
    db-config:
      id-type: assign_id