server:
  port: 8099
spring:
  datasource:
    url: jdbc:mysql://47.120.33.1:3306/heima?useSSL=false
    username: root
    password: 52ms1.MYSQL
    driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: cn.itcast.hotel.pojo